version: v2
global:
  runner:
    os_image: ubuntu

tasks:
  build-image:
    steps:
    - checkout
    - docker/build:
        image: nikhil
        tags: ["${CI_COMMIT_SHA}", "latest"]
        dockerfile: Dockerfile
        context: .
        
